### ISSUE TITLE
Użycie Autocomplete 

### ISSUE THREAD

**Issue by mnatan** [PZCharon/charon-frontend#11]
Chciałbym zobaczyć przykład jak użyć w projekcie [Autocomplete z biblioteki jquery UI](https://jqueryui.com/autocomplete/#remote-jsonp) do ściągania JSON'ów z backendu przy użyciu zapytań AJAX.

[Link do wątku z API w backendzie](https://github.com/PZCharon/charon-backend/issues/7)

Przykład może być gdziekolwiek, np na stronie głównej.

**Comment by s-nez** [comment]
Rozważcie też element <datalist>, który może pozwolić na autouzupełnianie bez JS.
Przykład (z [StackOverflow](http://stackoverflow.com/questions/13568609/autocomplete-text-input-for-html5/19779010#19779010):
```html
<input type="search" list="languages" placeholder="Pick a programming language..">

<datalist id="languages">
  <option value="PHP" />
  <option value="C++" />
  <option value="Java" />
  <option value="Ruby" />
  <option value="Python" />
  <option value="Go" />
  <option value="Perl" />
  <option value="Erlang" />
</datalist>
```
