### ISSUE TITLE
Informacja o wygaśnięciu sesji

### ISSUE THREAD

**Issue by s-nez** [PZCharon/charon-frontend#17]
W aktualnej implementacji, jeśli sesja wygaśnie, użytkownik przestaje mieć dostęp do zasobów wymagających autoryzacji (dostaje puste pola w ich miejsce), ale na stronie wciąż jest "zalogowany".

W momencie kiedy autoryzacja tokenem się nie powiodła, należy poinformować użytkownika o wygaśnięcu sesji i umożliwić ponowne zalogowanie.

**Comment by mnatan** [comment]
Fixed, closing
