### ISSUE TITLE
Użycie stałych do wypisywania informacji do debuggowania

### ISSUE THREAD

**Issue by s-nez** [PZCharon/charon-frontend#18]
W CharonFront::RESTUser i CharonFront::App zmienna leksykalna jest użyta do oznaczenia, czy wypisywać dodatkowe informacje, czy nie:
```perl
my $DEBUG = 1;
print ... if $DEBUG;
```
Tego rodzaju instrukcje powinny używać stałej, żeby ciągle nie sprawdzać warunku w środowisku produkcyjnym, gdzie DEBUG będzie fałszem.
```perl
use constant DEBUG => 1;
print ... if DEBUG;
```
W tym wypadku jeśli DEBUG jest fałszem, instrukcje zostaną usunięte z kodu w trakcie kompilacji i nie dodadzą dodatkowego narzutu w środowisku produkcyjnym.

[Więcej informacji](http://perldoc.perl.org/constant.html).

**Comment by mnatan** [comment]
Implemented, dzięki :+1:
