### ISSUE TITLE
Usunięcie Bootstrapa

### ISSUE THREAD

**Issue by s2bb** [PZCharon/charon-frontend#25]
Proszę o usunięcie bootstrapa

**Comment by mnatan** [comment]
Bootstrap jest podstawą naszego frontendu i jest w tym projekcie praktycznie niezbędny do RWD (#7).

Masz jakiś powód do tego żeby zastąpić tony ogarniętego frameworku CSS+HTML własnym kodem który ciężko napisać od zera?

Moim zdaniem nie ma na to czasu.

**Comment by s2bb** [comment]
Usuwamy ponieważ ta technologia jest zbędna na nasze potrzeby.
Otwieram ponownie i proszę o wykonanie zadania, w przeciwnym wypadku będzie to skutkować konsekwencjami.

**Comment by mnatan** [comment]
"[...] ta technologia jest zbędna na nasze potrzeby" - na jakiej podstawie tak twierdzisz?

Skoro byłeś tak miły żeby zabrać mi uprawnienia do assignowania zadań, to przepisz to zadanie dla @morlinq która zajmuje się widokami w projekcie. I zapytaj ją napierw o zdanie, co sądzi o tym że ma przepisać projekt od początku bez frameworku.

**Comment by morlinq** [comment]
Ominęły mnie chyba jakieś nowe ustalenia...?
Od początku była mowa o Bootstrapie i nikt nie zgłaszał sprzeciwu. Jaki sens ma usuwanie go teraz, skoro jest podstawą widoków (które zgodnie z #8 były specjalnie przepisywane)?

**Comment by s-nez** [comment]
Wypowiedź kogoś bardziej znającego się na temacie:
[You don't need Boostrap](http://fourkitchens.com/blog/article/you-dont-need-bootstrap) - [Ian Carrico](https://www.drupal.org/u/iamcarrico) (Drupal Association)

**Comment by mnatan** [comment]
Przekleję:

> ### What Bootstrap is good for
> [...] it is a good way to learn, and see how some interesting styling can be used. If you are new to front end work, or want to see how responsive web design works at a fundamental level, check out the code.
> [...]
> As this code will not need to be perfectly performant, and will not matter if its design steals from other UI elements, use Bootstrap.

Uważam, że autor podał solidne argumenty, że bootstrap nie daje "prawdziego RWD", jednak moim zdaniem całkiem łatwy w użyciu grid system będzie w naszym przypadku łatwy w użyciu i utrzymaniu.


Decyzja i tak należy do @morlinq i @ovk6. Dziewczyny najwięcej z tym pracują i musiałyby to przerobić.

**Comment by s-nez** [comment]
Ostatnia linijka cytatu jest trochę wyjęta z kontekstu:

**Comment by mnatan** [comment]
Ja zrozumiałem ten przekaz tak, że gdy używanie "kradzionych" elementów ui z innych stron ci nie przeszkadza, możesz użyć Bootstrapa. Moim zdaniem podobieństwo do innych bootstrapowych tworów nie przeszkadza nam w zupełności.

**Comment by s-nez** [comment]
Pominąłęś tutaj kwestię wydajności. Tam jest napisane, że skoro ten kod nie musi być jakoś specjalnie wydajny i nie przeszkadza nam podobieństwo do innych Boostrapowych stron, to wtedy można sobie zrobić w Boostrapie.

O ile podobieństwo do innych boostrapowych stron jakoś nam specjalnie nie przeszkadza, to wydajność nie jest kwestią, którą możemy sobie od tak pominąć. Co z tego, że będzie RWD jak na jakimś tańszym telefonie wszystko się będzie cięło?

**Comment by mnatan** [comment]
Pominąłem, bowiem mowa tu o javascriptowej części frameworku, której docelowo nie używamy. Boostrap jest "ciężki" ze względu na narzut jquery i dużą ilości pluginów wykonujących stale obliczenia docelowych rozmiarów wszystkich elementów.

Jeśli zaś mówimy o części css to najdłuższy jest zazwyczaj czas ładowania.

Z mojego doświadczenia wersja bootstrap.min.css + użycie proxy + kompresja rozwiązuje ten problem.

Dodatkowa ciekawa lekutra: http://www.zingdesign.com/5-reasons-not-to-use-twitter-bootstrap/

Tutaj autor wspomina:
> Bootstrap doesn’t work with JavaScript disabled

Postaram się więc zatem poruszyć go bez js w ramach issue #24 i zobaczę czy to faktycznie jest taki problem (zdania w internecie są podzielone i podejrzewam że uzależnienie od js to przeszłość.)

**Comment by s-nez** [comment]
> bootstrap.min.css + użycie proxy + kompresja rozwiązuje ten problem.

Jak się ma użycie proxy do rozwiązania tego problemu?

Z tego, co widzę to aktualnie front używa pełnej wersji boostrapa (a przynajmniej ją ładuje).

Jaka kompresja?

**Comment by mnatan** [comment]
http://www.quickonlinetips.com/archives/2015/01/load-bootstrap-faster/
oraz
http://www.quickonlinetips.com/archives/2013/05/css-files-load-faster/

Przez proxy miałem na myśli reverse proxy caching, dodatkowo wszyscy polecają CDN. Obie te rzeczy można uzyskać używając Bootstrap CDN:
```
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
````

Kompresja zaś jest wspomniana w artykułach, ale dodatkowo te CDN używają gzipowania transferu żeby szybciej dostarczać content.

**Comment by s-nez** [comment]
W pierwszym artykule polecają użyć wersji bootstrapa bez niepotrzebnych elementów, co kłóci się z użyciem gotowego CDN, który raczej nie dostarcza wszystkich kombinacji. To znaczy, że trzeba będzie zainwestować w CDN tylko po to, żeby ładować naszą wersję Boostrapa. Sugerowany tutaj MaxCDN ma najtańszy plan za 9$ miesięcznie. Zamierzasz pokryć te koszty?

**Comment by s2bb** [comment]
Jeśli jest możliwość pozbycia się js i uniknięcia problemu wydajnościowego przy użyciu bootstrapa to nie mam nic przeciwko. Jeśli tak się nie da to trzeba znaleźć alternatywę.

**Comment by ovk6** [comment]
Wykonano
