### ISSUE TITLE
Porządki w branchach

### ISSUE THREAD

**Issue by s2bb** [PZCharon/charon-frontend#27]
Proszę o przypisanie do obecnie istniejących branchy sensownych nazw.
Tak samo w przypadku nowych.

**Comment by mnatan** [comment]
Czy przez sensowne nazwy masz na myśli branching model? 

Oryginalnie dążyliśmy do tego: nvie.com/posts/a-successful-git-branching-model/

Ale nikt nie ogarniał i zostaliśmy przy per-developer branchach (które z jakiegoś nieokreślonego powodu dla dziewczyn nazywają się <username>-test).

Jestem za powrotem do gitflow i per-issue branchingu. 

Czy jest na to zgoda zespołu?

**Comment by s2bb** [comment]
Nie trzymamy się jakiegoś konkretnego modelu.
Branche mają jawnie mówić po co są tworzone i tyle.

**Comment by s2bb** [comment]
Od teraz przymujemy tylko pull-requesty do develop.

**Comment by mnatan** [comment]
Approved :+1:

@s2bb Zajmiesz się releasowaniem developa do mastera i tworzeniem tagów?

**Comment by s2bb** [comment]
Takie jest moje zadanie.

**Comment by s2bb** [comment]
Wykonano
