### ISSUE TITLE
Odpytywanie backendu z wykorzystaniem id

### ISSUE THREAD

**Issue by s-nez** [PZCharon/charon-frontend#28]
Zapytania o konkretny element zasobu, jak np. GET /users/:login powinny być wykonywane z użyciem id. To znaczy, że w momencie autoryzacji użytkownika, razem z tokenem autoryzacyjnym frontend dostanie jeszcze id użytkownika. Tego id należy używać do komunikacji z backendem, więc powyższy przykład zmieni się na GET /users/:id.

Wszystkie nowe funkcjonalności, które będą wymagały dostępu do konkretengo elementu zasobu będą implementowane z dostępem po id, a istniejące funkcjonalności (chyba tylko /users) zostaną zmodyfikowane, żeby używać id.

Oczywiście /authorize nie będzie wymagało id, bo to nie ma sensu.

# Dlaczego tak?

Z punktu widzenia frontendu, rożnica w odpytywaniu po loginie (nazwie) i odpytywaniu po id jest znikoma. Zamiast jednego parametru sesji trzeba będzie użyć innego.

Z punktu widzenia backendu jest to dużo wydajniejsze rozwiązanie, ponieważ można wykorzystać bezpośrednio numeryczne klucze główne bazy danych. Dodatkowo, w przypadku innych zasobów, jak np. formularze, których może być dużo, a ich widoczność będzie się rożniła w zależności od użytkownika, używanie nazwy do indentyfikacji wprowadzi niepotrzebne komplikacje.

**Comment by s-nez** [comment]
Ostatni commit w developie z wersją działającą na nazwach zamiast id: b47afc5ea52215874cc2aa302341942ac8c4f921

**Comment by s2bb** [comment]
Wykonano.
