### ISSUE TITLE
Angular - strona nie działa bez JS

### ISSUE THREAD

**Issue by s-nez** [PZCharon/charon-frontend#40]
Wersja frontendu z brancha angular jest całkowicie niefunkcjonalna bez JS. Wyświetla tylko mało pomocny napis "Wczytywanie".

DoD: Podstawowa funkcjonalność strony jest dostępna bez JS.

**Comment by mnatan** [comment]
Co rozumiesz przez "Podstawową funkcjonalność"? Mogę wyświetlić dowolny statyczny html pokroju "Ta strona nie działa bez javascriptu", ale angular jest z założenia frameworkiem JS i robienie czegoś więcej będzie redundantne.

**Comment by s-nez** [comment]
Informacja typu "Ta strona nie działa bez JavaScriptu" na pewno będzie lepsza niż "Wczytywanie".
