### ISSUE TITLE
Angular - użytkownik wyświetla się jako "Marcin Natanek"

### ISSUE THREAD

**Issue by s-nez** [PZCharon/charon-frontend#42]
Zarejestrowałem użytkownika o nazwisku "Adam Roman", ale po zalogowaniu się do systemu w prawym górnym rogu wyświetla się "Marcin Natanek". Dodatkowo w menu rozwijanym z nazwy użytkownika są przekreślone TODO, które nic nie robią.

![Screenshot](https://ww2.ii.uj.edu.pl/~z1100809/share/charon_user_name.png)

**Comment by mnatan** [comment]
Powiązane z: https://github.com/PZCharon/charon-backend/issues/21
Obecnie zapytanie jest mockowane
