### ISSUE TITLE
Angular - informacje kontaktowe wyświetlają się w JSON

### ISSUE THREAD

**Issue by s-nez** [PZCharon/charon-frontend#43]
Informacje w zakładce "Kontakt" wyświetlają się w formacie JSON. Nie jest to najlepszy format do wyświetlania końcowemu użytkownikowi.

![Screenshot](https://ww2.ii.uj.edu.pl/~z1100809/share/json_contact.png)

**Comment by mnatan** [comment]
To nie bug, to jest kolejne TODO.

**Comment by morlinq** [comment]
e399d6ba56031d5e5e0643002f48d028b33755ac
