### ISSUE TITLE
Responsive web design

### ISSUE THREAD

**Issue by mnatan** [PZCharon/charon-frontend#7]
Strona powinna dobrze wyświetlać się na urządzeniach wszelkiego rodzaju, zwłaszcza chodzi tu o smartfony. Zadanie polega na przejrzeniu templatek i dostosowaniu html+css do dobroci oferowanych przez bootstrapa.

**Comment by mnatan** [comment]
Strona rozwala się poniżej 1000px. Fix w ramach tego issue.

**Comment by s-nez** [comment]
@morlinq jak wygląda postęp tego issue? Jest już kilka dni po terminie.

**Comment by mnatan** [comment]
To issue nie zostało rozwiązane. @s2bb dlaczego je zamknąłeś bez żadnego komentarza?

**Comment by s2bb** [comment]
To nie jest temat na issue, dlatego zamykam.

**Comment by mnatan** [comment]
[Ten komentarz](https://github.com/PZCharon/charon-frontend/issues/7#issuecomment-199433879) wyraźnie opisuje co nie zostało zrobione. Zadanie polega na dostosowaniu wyglądu strony do urządzeń mobilnych.

Co masz na myśli przez "To nie jest temat na issue"?
